### ISSUE TITLE
ValueError: floating-point under-/overflow occurred.

### ISSUE THREAD

**Issue by dreamflasher** [Mendeley/mrec#11]
Issuing:
mrec_train -n8 --train=filtered_p1_u40_t50.txt.train.matrix.idx --input_format=tsv --outdir p1u40t50

Yields:
[2014-06-02 13:44:20,204] INFO: 96556 users and 30924 items
[2014-06-02 13:44:20,658] INFO: running 8 tasks in parallel across ipython engines...
Traceback (most recent call last):
  File "/usr/local/anaconda/bin/mrec_train", line 9, in <module>
    load_entry_point('mrec==0.3.1', 'console_scripts', 'mrec_train')()
  File "build/bdist.linux-x86_64/egg/mrec/examples/train.py", line 136, in main
  File "build/bdist.linux-x86_64/egg/mrec/parallel/item_similarity.py", line 39, in run
  File "/usr/local/anaconda/lib/python2.7/site-packages/IPython/parallel/client/asyncresult.py", line 118, in get
    raise self._exception
IPython.parallel.error.CompositeError: one or more exceptions from call to method: process
[3:apply]: ValueError: floating-point under-/overflow occurred.
[1:apply]: ValueError: floating-point under-/overflow occurred.
[0:apply]: ValueError: floating-point under-/overflow occurred.
[5:apply]: ValueError: floating-point under-/overflow occurred.

Usually this happens due to too large regularization learning rate, but there seems to be no option to change the learning rate for SLIM.

**Comment by huHHhhuhu** [comment]
Hello DreamFlasher,

I'm using mrec now, however, I can't find where mrec_prepare, mrec_train and mrec_predict scripts are. May I ask you where they are?

thx!

Sincerely yours,
David
